### ISSUE TITLE
mera fb nahi chal rah

### ISSUE THREAD

**Issue by namanyayg** [akshatmittal/akshatmittal.github.io#1]
fb pagal ho rha hai, 361ms ping etc. Baakio ke saath ek slack bana de please jaha mein invited hu? sorry to spam your issues.

**Comment by akshatmittal** [comment]
GitHub Issues, seriously!? :3

WhatsApp hi kar deta.

**Comment by namanyayg** [comment]
#justnerdthings

And thanks a ton for the quick response :P
